import RatingBadge, { ratingTextColor } from "./RatingBadge";
import Collapsible from "./Collapsible";
import type { ResearchResult } from "@/lib/types";

function StatCard({ label, value }: { label: string; value: React.ReactNode }) {
  return (
    <div className="rounded-lg bg-gray-50 px-4 py-3 dark:bg-gray-900">
      <div className="text-xs uppercase tracking-wide text-gray-500 dark:text-gray-400">{label}</div>
      <div className="mt-1 text-lg font-semibold text-gray-900 dark:text-gray-100">{value}</div>
    </div>
  );
}

function fmtScore(n: number | null | undefined): string {
  if (n === null || n === undefined) return "N/A";
  return `${n >= 0 ? "+" : ""}${n.toFixed(1)}`;
}

function fmtMoney(n: number | null | undefined): string {
  if (n === null || n === undefined) return "N/A";
  return `$${n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export default function ReportView({
  result,
  jobId,
  latencySeconds,
}: {
  result: ResearchResult;
  jobId: string;
  latencySeconds: number | null;
}) {
  const rd = result.report_data || {};
  const rec = rd.recommendation || { rating: "Insufficient Data", basis: "" };
  const confidence = rd.confidence_scores || {};
  const valuation = rd.valuation_analysis || {};
  const monteCarlo = valuation.monte_carlo;
  const mlClassifier = valuation.ml_classifier;
  const consensus = rd.institutional_consensus?.recommendation_consensus;
  const news = rd.news_sources || {};
  const summary = rd.narrative?.["Executive Summary"];

  return (
    <div className="mt-8 space-y-6">
      {rd.mode === "comparison" && result.peer_ticker && (
        <div className="rounded-lg bg-blue-50 px-4 py-2 text-sm text-blue-800 dark:bg-blue-950 dark:text-blue-300">
          Comparing {result.ticker} vs {result.peer_ticker}
        </div>
      )}

      <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Report Ready</h2>

      <div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-200">
        <strong>This report is a predictive analytical signal generated by an automated research tool, not
        personalized investment advice.</strong> Past performance and model outputs are not guarantees of future
        results. Consult a licensed financial advisor before making investment decisions.
      </div>

      <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
        <div className="md:col-span-1 space-y-3">
          <RatingBadge rating={rec.rating} />
          <p className="text-sm text-gray-600 dark:text-gray-400">{rec.basis}</p>
          {rec.composite_score !== null && rec.composite_score !== undefined && (
            <div className="grid grid-cols-3 gap-2">
              <StatCard label="DCF Score" value={fmtScore(rec.dcf_score)} />
              <StatCard label="Relative Score" value={fmtScore(rec.relative_score)} />
              <StatCard label="Composite" value={fmtScore(rec.composite_score)} />
            </div>
          )}
          {rec.confidence_flag && (
            <div className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-200">
              <strong>Low-confidence signal:</strong> {rec.confidence_flag}
            </div>
          )}
        </div>
        <div className="md:col-span-2 grid grid-cols-3 gap-2 content-start">
          <StatCard label="Overall Score" value={confidence["Overall Score"] ?? "N/A"} />
          <StatCard label="Grounding" value={confidence["Grounding (%)"] ?? "N/A"} />
          <StatCard label="Latency" value={latencySeconds ? `${latencySeconds.toFixed(1)}s` : "N/A"} />
        </div>
      </div>

      {summary && (
        <Collapsible title="Executive Summary preview" defaultOpen>
          <p className="whitespace-pre-wrap text-sm text-gray-800 dark:text-gray-200">{summary}</p>
        </Collapsible>
      )}

      {monteCarlo && (
        <Collapsible title="Monte Carlo Simulation (intrinsic value distribution)">
          <p className="mb-3 text-xs text-gray-500 dark:text-gray-400">
            {monteCarlo.n_samples.toLocaleString()} samples over growth rate / WACC / terminal growth -- a
            distribution around the DCF point estimate, not another verdict. Not yet folded into the recommendation
            composite above.
          </p>
          <div className="grid grid-cols-3 gap-2">
            <StatCard label="Mean Intrinsic Value" value={fmtMoney(monteCarlo.mean)} />
            <StatCard label="Median" value={fmtMoney(monteCarlo.median)} />
            <StatCard label="Probability Undervalued" value={`${(monteCarlo.prob_undervalued * 100).toFixed(1)}%`} />
          </div>
          <p className="mt-3 text-xs text-gray-500 dark:text-gray-400">
            90% CI: {fmtMoney(monteCarlo.ci_lower)} - {fmtMoney(monteCarlo.ci_upper)} | 25th-75th percentile:{" "}
            {fmtMoney(monteCarlo.p25)} - {fmtMoney(monteCarlo.p75)} | Std Dev: {fmtMoney(monteCarlo.std_dev)}
          </p>
        </Collapsible>
      )}

      {mlClassifier && (
        <Collapsible title="ML Valuation Classifier (informational only)">
          <p className="mb-3 text-xs text-gray-500 dark:text-gray-400">
            Trained on FinSight&apos;s own point-in-time backtest data. <strong>Not part of the recommendation
            above</strong> -- it has no accuracy track record yet, unlike DCF and relative valuation, both of which
            have been backtested.
          </p>
          <div className="grid grid-cols-2 gap-2">
            <StatCard label="ML Verdict" value={mlClassifier.verdict} />
            <StatCard
              label="Confidence"
              value={`${((mlClassifier.probabilities[mlClassifier.verdict] || 0) * 100).toFixed(1)}%`}
            />
          </div>
          <p className="mt-2 text-xs text-gray-500 dark:text-gray-400">
            Model: {mlClassifier.model_name.replace(/_/g, " ")}
          </p>
        </Collapsible>
      )}

      {consensus && (
        <Collapsible title="Institutional Consensus Score" defaultOpen>
          <div className="mb-3">
            <div className="text-3xl font-bold text-gray-900 dark:text-gray-100">{consensus.score}%</div>
            <div className="font-medium text-gray-600 dark:text-gray-400">{consensus.label}</div>
          </div>
          <p className="mb-3 text-xs text-gray-500 dark:text-gray-400">{consensus.methodology}</p>
          <div className="mb-3 space-y-1">
            <div className="font-semibold text-sm text-gray-900 dark:text-gray-100">Market Consensus</div>
            {consensus.institutional_ratings.map((r, i) => (
              <div key={i} className="flex justify-between text-sm">
                <span className="text-gray-700 dark:text-gray-300">{r.firm}</span>
                <span className={`font-semibold ${ratingTextColor(r.rating.charAt(0).toUpperCase() + r.rating.slice(1).toLowerCase())}`}>
                  {r.rating}
                </span>
              </div>
            ))}
          </div>
          <div className="mb-2">
            <div className="font-semibold text-sm text-gray-900 dark:text-gray-100">FinSight Recommendation</div>
            <RatingBadge rating={consensus.finsight_rating} />
          </div>
          <div>
            <div className="font-semibold text-sm text-gray-900 dark:text-gray-100">Market Summary</div>
            <p className="text-sm text-gray-700 dark:text-gray-300">{consensus.summary}</p>
          </div>
        </Collapsible>
      )}

      <Collapsible title={`News Sources Used in This Analysis (${news.total_retrieved || 0} retrieved, ${news.total_selected || 0} used)`}>
        {!news.total_retrieved ? (
          <p className="text-sm text-gray-500 dark:text-gray-400">No recent news coverage was found for this company.</p>
        ) : (
          <div className="space-y-3">
            <p className="text-xs text-gray-500 dark:text-gray-400">
              Every article retrieved is shown here, not just the ones used in the analysis above -- so you can judge
              whether the selection looks reasonable, not only what the model chose to reference.
            </p>
            {news.all_articles?.map((a, i) => (
              <div key={i} className="text-sm">
                <a href={a.url} target="_blank" rel="noreferrer" className="font-medium text-blue-600 hover:underline dark:text-blue-400">
                  {a.headline}
                </a>
                <div className="text-xs text-gray-500 dark:text-gray-400">
                  {a.source} — {a.date} — {a.used_in_analysis ? "✅ Used" : "⬜ Retrieved, not used"}
                </div>
              </div>
            ))}
          </div>
        )}
      </Collapsible>

      <a
        href={`/api/research/${jobId}/pdf`}
        download={`${result.ticker}_FinSight_Research_Report.pdf`}
        className="inline-block rounded-lg bg-gray-900 px-5 py-2.5 text-sm font-semibold text-white hover:bg-gray-700 dark:bg-gray-100 dark:text-gray-900 dark:hover:bg-white"
      >
        Download Full Research Report (PDF)
      </a>
    </div>
  );
}
